### ISSUE TITLE
new readme

### ISSUE THREAD

**Issue by SophieDeBenedetto** [learn-co-curriculum/mass-assignment-metaprogramming#1]
brand new readme 

@jmburges

**Comment by jmburges** [comment]
So this readme is great, but I really really don't think metaprogramming belongs in the intro stuff. How often do you meta-program?

**Comment by jmburges** [comment]
dont' delete it, I just think it belongs like WAY later in the course

**Comment by AnnJohn** [comment]
Fixed. closing issue.
