### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by anglinchristina** [learn-co-curriculum/mass-assignment-metaprogramming#12]
This code snippet has an extra set of () around "#{key}=":

`class User
  attr_accessor :name, :user_name, :age, :location, :bio
 
  def initialize(attributes)
    attributes.each {|key, value| self.send(("#{key}="), value)}
  end
end`

**Comment by gj** [comment]
Hi @anglinchristina !

Those parentheses are harmless. 🙂
