### ISSUE TITLE
#send method example has parenthesis around first value. 

### ISSUE THREAD

**Issue by mtrussell** [learn-co-curriculum/mass-assignment-metaprogramming#13]
Directly under the section heading "MASS ASSIGNMENT AND METAPROGRAMMING" there is a code example using the #send method. The first argument is surrounded with parenthesis.

`class User
  attr_accessor :name, :user_name, :age, :location, :bio
 
  def initialize(attributes)
    attributes.each {|key, value| self.send(**("#{key}=")**, value)}
  end
end`

Other examples of the #send method don't use this, and I looked up other examples online and couldn't find any others using the parenthesis. I just wanted to check that this wasn't a typo. 

However, if it isn't a typo, what is the use of the parenthesis?

**Comment by gj** [comment]
Hi @mtrussell !

The parens can just be used to group expressions. In this case, they're harmless.

Hope that clears it up!
